plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.sparsemetronome'
version = '0.1.0'

android {
  namespace "expo.modules.sparsemetronome"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  compileOptions {
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
}