import { StyleSheet } from "react-native";
import type { ViewStyle, TextStyle, ImageStyle } from "react-native";
import Colors from "@/constants/colors";
import type { ScaleValues } from "@/lib/scale";

export const make_styles = (C: typeof Colors, S: ScaleValues) => _make_styles_inner(C, S) as unknown as {
  [K in keyof ReturnType<typeof _make_styles_inner>]: ViewStyle & TextStyle & ImageStyle;
};

const _make_styles_inner = (C: typeof Colors, S: ScaleValues) => StyleSheet.create({
  touchArea: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    cursor: "grab" as any,
    userSelect: "none" as any,
  },
  dialContainer: {
    width: S.dialSize,
    height: S.dialSize,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden" as const,
  },
  dial: {
    width: S.dialSize,
    height: S.dialSize,
    borderRadius: S.dialRadius,
  },
  centerArea: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
  },
  signatureRow: {
    position: "absolute",
    width: S.dialSize * 0.6,
    height: S.dialSize * 0.6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  digitalSignature: {
    fontFamily: "SpaceGrotesk_700Bold",
    fontSize: S.dialSize * 0.1,
    color: C.text,
    opacity: 0.15,
  },
  centerImageContainer: {
    position: "absolute",
    width: S.ms(130),
    height: S.ms(130),
    borderRadius: S.ms(65),
    overflow: "hidden",
    opacity: 0.35,
  },
  centerImage: {
    width: S.ms(130),
    height: S.ms(130),
    borderRadius: S.ms(65),
  },
  centerGlow: {
    position: "absolute",
    width: S.ms(120),
    height: S.ms(120),
    borderRadius: S.ms(60),
    opacity: 0,
  },
  playButton: {
    alignItems: "center",
    justifyContent: "center",
    padding: 8,
  },
  playButtonPressed: {
    transform: [{ scale: 0.85 }],
    opacity: 0.6,
  },
  hintText: {
    fontFamily: "SpaceGrotesk_400Regular",
    fontSize: 11,
    letterSpacing: 1,
    color: C.text,
    opacity: 0.5,
  },
  barFadeGradient: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 10,
  },
  barFadeGradientBottom: {
    width: "100%" as any,
    zIndex: 10,
  },
  barTimerOverlay: {
    flex: 1,
    backgroundColor: C.scrim,
    justifyContent: "center",
    alignItems: "center",
  },
  barTimerCard: {
    borderRadius: 16,
    padding: 24,
    width: S.ms(220, 0.5),
    alignItems: "center",
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surface,
  },
  barTimerHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  barTimerTitle: {
    fontFamily: "SpaceGrotesk_700Bold",
    fontSize: 16,
    color: C.text,
  },
  barTimerInput: {
    fontFamily: "SpaceGrotesk_700Bold",
    fontSize: 32,
    textAlign: "center",
    color: C.text,
    padding: 8,
    borderBottomWidth: 2,
    width: "100%" as any,
  },
  barTimerHint: {
    fontSize: 11,
    marginTop: 8,
    fontFamily: "SpaceGrotesk_400Regular",
    color: C.textTertiary,
  },
  barTimerSetBtn: {
    marginTop: 16,
    paddingHorizontal: 32,
    paddingVertical: 10,
    borderRadius: 8,
  },
  barTimerSetText: {
    fontFamily: "SpaceGrotesk_700Bold",
    fontSize: 14,
    color: C.white,
  },
  barClockDots: {
    flexDirection: "row",
    gap: 4,
    marginTop: 3,
  },
  barClockDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
  },
  barInfoCol: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: S.ms(48, 0.4),
  },
  barInfoText: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: S.ms(12, 0.4),
    letterSpacing: 0.5,
    color: C.text,
  },
  dropTargetRing: {
    position: "absolute",
    borderWidth: 2,
    borderStyle: "dashed" as any,
    opacity: 0.8,
  },
  subdivBadge: {
    position: "absolute",
    bottom: -4,
    right: -4,
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  subdivBadgeText: {
    fontFamily: "SpaceGrotesk_700Bold",
    fontSize: 9,
    color: C.text,
  },
  centerDropRing: {
    position: "absolute",
    width: S.ms(110),
    height: S.ms(110),
    borderRadius: S.ms(55),
    borderWidth: 2,
    borderStyle: "dashed" as any,
    opacity: 0.8,
  },
  centerDropLabel: {
    fontFamily: "SpaceGrotesk_700Bold",
    fontSize: 11,
    letterSpacing: 2,
    marginTop: 8,
    color: C.text,
    opacity: 0.9,
  },
  barModeContainer: {
    flex: 1,
    width: "100%" as any,
  },
  barTopRowCenter: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 40,
    paddingBottom: 4,
  },
  barBottomRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    gap: 16,
  },
  barModeCloseBtn: {
    width: S.ms(32, 0.4),
    height: S.ms(32, 0.4),
    borderRadius: S.ms(16, 0.4),
    backgroundColor: C.overlay06,
    alignItems: "center",
    justifyContent: "center",
  },
  barPlayBtn: {
    width: S.ms(36, 0.5),
    height: S.ms(36, 0.5),
    borderRadius: S.ms(18, 0.5),
    backgroundColor: C.overlay06,
    alignItems: "center",
    justifyContent: "center",
  },
  barLoopBtn: {
    width: S.ms(36, 0.5),
    height: S.ms(36, 0.5),
    borderRadius: S.ms(18, 0.5),
    backgroundColor: C.overlay06,
    alignItems: "center",
    justifyContent: "center",
  },
  barTimeSigRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  barTimeSigBtn: {
    width: S.ms(32, 0.5),
    height: S.ms(32, 0.5),
    borderRadius: S.ms(16, 0.5),
    backgroundColor: C.overlay08,
    alignItems: "center",
    justifyContent: "center",
  },
  barMeasureInner: {
    flex: 1,
    gap: 0,
  },
  barBeatWrapper: {
    flexDirection: "row",
    alignItems: "stretch",
    overflow: "visible" as any,
  },
  barBeatLabel: {
    width: S.ms(22, 0.4),
    alignItems: "center",
    justifyContent: "center",
  },
  barBeatLabelText: {
    fontFamily: "SpaceGrotesk_700Bold",
    fontSize: S.ms(13, 0.4),
    color: C.text,
  },
  barBeatContent: {
    flex: 1,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: C.overlay08,
    overflow: "visible" as any,
  },
  barNoteCell: {
    flex: 1,
    alignItems: "stretch",
    justifyContent: "center",
  },
  barNoteFill: {
    flex: 1,
    borderRadius: 4,
  },
  noteSampleBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 3,
    borderRadius: 0,
    zIndex: 10,
  },
  barBeatEndLine: {
    width: 1.5,
    marginLeft: 0,
    opacity: 0.4,
  },
  barMeasureOuter: {
    flex: 1,
    flexShrink: 1,
    width: "100%" as any,
    paddingHorizontal: 0,
    overflow: "hidden",
  },
  barScrollView: {
    flexGrow: 0,
  },
  barScrollFade: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 20,
    backgroundColor: "transparent",
  },
  barBeatWrapperActive: {
    backgroundColor: C.overlay03,
  },
  barModeHandle: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: S.ms(8, 0.4),
    paddingHorizontal: S.ms(24, 0.4),
    minWidth: S.ms(80, 0.4),
    minHeight: S.ms(36, 0.4),
    backgroundColor: C.overlay05,
    borderRadius: S.ms(12, 0.3),
  },
  barModeHandleLandscape: {
    position: "absolute" as const,
    right: -30,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    paddingVertical: 12,
    paddingHorizontal: 4,
    backgroundColor: C.overlay07,
    borderRadius: 8,
  },
  noteModeHandleLandscape: {
    position: "absolute" as const,
    left: -30,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    paddingVertical: 12,
    paddingHorizontal: 4,
    backgroundColor: C.overlay07,
    borderRadius: 8,
  },
  landscapeModeBtn: {
    alignItems: "center" as const,
    justifyContent: "center" as const,
    paddingVertical: S.ms(10, 0.4),
    paddingHorizontal: S.ms(4, 0.3),
    backgroundColor: C.overlay07,
    borderRadius: S.ms(8, 0.3),
  },
  barSubdivisionSlot: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
});
