import { StyleSheet } from "react-native";
import { Radius, Spacing, FontSize } from "@/constants/tokens";

export const makeStyles = (_C: any, _S: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    topBar: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: Spacing.md,
      paddingBottom: 10,
      borderBottomWidth: 1,
      gap: Spacing.xs ?? 4,
    },
    iconBtn: {
      padding: 4,
    },
    playBtnWrapper: {
      alignItems: "center",
    },
    prepareBarTrack: {
      width: 32,
      height: 2,
      borderRadius: 1,
      backgroundColor: "rgba(128,128,128,0.3)",
      overflow: "hidden",
      marginTop: 2,
    },
    prepareBarFill: {
      height: 2,
      borderRadius: 1,
    },
    topTitle: {
      flex: 1,
      fontFamily: "SpaceGrotesk_600SemiBold",
      fontSize: FontSize.body,
    },
    savedToast: {
      fontFamily: "SpaceGrotesk_500Medium",
      fontSize: FontSize.small,
    },
    saveBtn: {
      paddingHorizontal: Spacing.md,
      paddingVertical: 7,
      borderRadius: Radius.md,
    },
    saveBtnText: {
      fontFamily: "SpaceGrotesk_600SemiBold",
      fontSize: FontSize.small,
      color: "#fff",
    },
    partTabsScroll: {
      borderBottomWidth: 1,
      maxHeight: 40,
    },
    partTabsContent: {
      paddingHorizontal: Spacing.md,
    },
    partTab: {
      paddingHorizontal: Spacing.md,
      paddingVertical: 8,
    },
    partTabText: {
      fontFamily: "SpaceGrotesk_500Medium",
      fontSize: FontSize.small,
    },
    selectionBar: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: Spacing.md,
      paddingVertical: 6,
      borderBottomWidth: 1,
      gap: 6,
    },
    selectionLabel: {
      fontFamily: "SpaceGrotesk_400Regular",
      fontSize: FontSize.small,
    },
    selBarBtn: {
      borderWidth: 1,
      borderRadius: Radius.sm,
      paddingHorizontal: 10,
      paddingVertical: 4,
      alignItems: "center",
      justifyContent: "center",
      minWidth: 32,
    },
    selBarBtnText: {
      fontSize: 16,
      fontFamily: "serif",
    },
    scoreScroll: {
      flex: 1,
    },
    scoreContent: {
      gap: 0,
    },
    scoreHeader: {
      alignItems: "center",
      paddingVertical: Spacing.md,
      gap: 4,
    },
    scoreTitle: {
      fontFamily: "SpaceGrotesk_700Bold",
      fontSize: FontSize.subtitle,
    },
    scoreMeta: {
      fontFamily: "SpaceGrotesk_400Regular",
      fontSize: FontSize.small,
    },
    inputHint: {
      fontFamily: "SpaceGrotesk_400Regular",
      fontSize: FontSize.small,
      textAlign: "center",
      marginBottom: 8,
      opacity: 0.7,
    },
    addMeasureRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "center",
      gap: 6,
      paddingVertical: 6,
      paddingHorizontal: Spacing.md,
      borderWidth: 1,
      borderRadius: Radius.sm,
      borderStyle: "dashed",
      marginBottom: 8,
    },
    addMeasureRowText: {
      fontFamily: "SpaceGrotesk_500Medium",
      fontSize: FontSize.small,
    },
    trashZone: {
      width: 36,
      height: 44,
      borderWidth: 1,
      borderRadius: Radius.sm,
      alignItems: "center",
      justifyContent: "center",
      marginLeft: 4,
    },
    zoomViewWrapper: {
      borderTopWidth: 1,
      paddingVertical: 6,
      paddingHorizontal: Spacing.md,
      maxHeight: 180,
    },
    zoomViewLabel: {
      fontFamily: "SpaceGrotesk_400Regular",
      fontSize: 10,
      marginBottom: 4,
      letterSpacing: 0.5,
    },
    linkedEntryBadge: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 4,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 3,
      borderRadius: 6,
      borderWidth: 1,
      marginHorizontal: Spacing.md,
      marginBottom: 4,
    },
    linkedEntryBadgeText: {
      fontFamily: "SpaceGrotesk_400Regular",
      fontSize: 10,
      letterSpacing: 0.3,
      flexShrink: 1,
    },
    playbackSection: {
      borderBottomWidth: 1,
      paddingBottom: 8,
      marginBottom: 8,
    },
    playbackSectionTitle: {
      fontFamily: "SpaceGrotesk_500Medium",
      fontSize: FontSize.small,
      marginBottom: 6,
      marginTop: 4,
    },
    paletteWrapper: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 4,
    },
    symbolModalBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
      padding: Spacing.lg,
    },
    symbolModalCard: {
      width: "100%",
      maxWidth: 400,
      maxHeight: "70%",
      borderRadius: Radius.lg,
      borderWidth: 1,
      padding: Spacing.lg,
    },
    symbolModalTitle: {
      fontFamily: "SpaceGrotesk_600SemiBold",
      fontSize: FontSize.body,
      marginBottom: 2,
    },
    symbolModalSub: {
      fontFamily: "SpaceGrotesk_400Regular",
      fontSize: FontSize.small,
      marginBottom: Spacing.md,
    },
    symbolModalList: {
      maxHeight: 320,
      marginBottom: Spacing.md,
    },
    symbolRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      gap: 8,
    },
    symbolRowSym: {
      width: 36,
      fontFamily: "SpaceGrotesk_600SemiBold",
      fontSize: FontSize.body,
      textAlign: "center",
    },
    symbolRowLabel: {
      flex: 1,
      fontFamily: "SpaceGrotesk_400Regular",
      fontSize: FontSize.small,
    },
    symbolModalClose: {
      borderRadius: Radius.md,
      paddingVertical: 10,
      alignItems: "center",
    },
    symbolModalCloseText: {
      fontFamily: "SpaceGrotesk_600SemiBold",
      fontSize: FontSize.small,
      color: "#fff",
    },
    ctxMenuItem: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      paddingVertical: 12,
      paddingHorizontal: 4,
      borderBottomWidth: 1,
      gap: 10,
    },
    ctxMenuLabel: {
      fontFamily: "SpaceGrotesk_400Regular",
      fontSize: FontSize.body,
      flex: 1,
    },
    drawerContainer: {
      borderWidth: 1,
      borderRadius: Radius.sm,
      marginTop: 8,
      overflow: "hidden" as const,
    },
    drawerHeader: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      justifyContent: "space-between" as const,
      paddingHorizontal: Spacing.md,
      paddingVertical: 8,
      borderBottomWidth: 1,
    },
    drawerHeaderText: {
      fontFamily: "SpaceGrotesk_500Medium",
      fontSize: FontSize.small,
    },
    drawerContent: {
      paddingHorizontal: Spacing.md,
      paddingVertical: 8,
      gap: 8,
    },
    drawerRow: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 6,
      flexWrap: "wrap" as const,
    },
    drawerFieldLabel: {
      fontFamily: "SpaceGrotesk_400Regular",
      fontSize: 10,
      minWidth: 72,
    },
    drawerInput: {
      borderWidth: 1,
      borderRadius: Radius.sm,
      paddingHorizontal: 8,
      paddingVertical: 5,
      fontFamily: "SpaceGrotesk_400Regular",
      fontSize: FontSize.small,
      minWidth: 60,
      maxWidth: 90,
    },
    drawerApplyBtn: {
      borderRadius: Radius.sm,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    drawerApplyBtnText: {
      fontFamily: "SpaceGrotesk_600SemiBold",
      fontSize: 11,
      color: "#fff",
    },
    drawerClearBtn: {
      borderRadius: Radius.sm,
      borderWidth: 1,
      paddingHorizontal: 8,
      paddingVertical: 5,
    },
    drawerClearBtnText: {
      fontFamily: "SpaceGrotesk_400Regular",
      fontSize: 11,
    },
    refOpacityBtn: {
      position: "absolute",
      top: 6,
      right: 6,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      borderWidth: 1,
    },
    refOpacityLabel: {
      fontFamily: "SpaceGrotesk_600SemiBold",
      fontSize: 11,
    },
    metaFieldLabel: {
      fontFamily: "SpaceGrotesk_500Medium",
      fontSize: FontSize.small,
      marginTop: 10,
      marginBottom: 4,
    },
    metaInput: {
      borderWidth: 1,
      borderRadius: Radius.sm,
      paddingHorizontal: 10,
      paddingVertical: 8,
      fontFamily: "SpaceGrotesk_400Regular",
      fontSize: FontSize.body,
    },
    metaInputMulti: {
      height: 64,
      textAlignVertical: "top" as const,
    },
    diffRow: {
      flexDirection: "row" as const,
      flexWrap: "wrap" as const,
      gap: 6,
      marginBottom: 4,
    },
    diffBtn: {
      borderWidth: 1,
      borderRadius: Radius.sm,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    diffBtnText: {
      fontFamily: "SpaceGrotesk_500Medium",
      fontSize: FontSize.small,
    },
  });
