import { Platform, StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const make_styles = (C: typeof Colors) => StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 80,
  },
  sheet: {
    backgroundColor: C.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.border,
    padding: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  title: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 18,
    color: C.text,
    letterSpacing: 0.5,
  },
  usernameSection: {
    gap: 10,
  },
  usernameInput: {
    height: 42,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 14,
    color: C.text,
    backgroundColor: C.surfaceLight,
  },
  tabBar: {
    flexDirection: "row",
    gap: 10,
    marginVertical: 4,
  },
  tabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: C.border,
    backgroundColor: C.surfaceLight,
  },
  tabBtnActive: {
    backgroundColor: C.accentDim,
  },
  tabBtnText: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 13,
    color: C.textSecondary,
  },
  section: {
    gap: 10,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionLabel: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 14,
    color: C.text,
    flex: 1,
  },
  sectionValue: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 14,
    color: C.accent,
    minWidth: 40,
    textAlign: "right" as const,
  },
  sidebarTab: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: C.border,
    marginBottom: 4,
  },
  verticalDivider: {
    width: 1,
    marginHorizontal: 8,
    backgroundColor: C.border,
  },
  divider: {
    height: 1,
    backgroundColor: C.border,
    marginVertical: 16,
  },
  sliderContainer: {
    height: 48,
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  sliderTrack: {
    height: 10,
    borderRadius: 5,
    backgroundColor: C.surfaceLight,
    overflow: "hidden",
  },
  sliderFill: {
    height: "100%",
    backgroundColor: C.accent,
    borderRadius: 5,
  },
  sliderThumb: {
    position: "absolute",
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: C.accent,
    marginLeft: -5,
    top: 11,
    borderWidth: 2,
    borderColor: C.surface,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
      },
      android: {
        elevation: 4,
      },
      web: {
        boxShadow: "0 2px 6px rgba(0,0,0,0.3)",
      },
    }),
  },
  volumeWarning: {
    fontSize: 11,
    color: "#FF6B35",
    paddingHorizontal: 8,
    paddingTop: 4,
    paddingBottom: 2,
    fontFamily: "Inter_400Regular",
  },
  sliderLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 8,
  },
  sliderLabelText: {
    fontFamily: "SpaceGrotesk_400Regular",
    fontSize: 10,
    color: C.textTertiary,
    letterSpacing: 0.5,
  },
  soundSetGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  soundSetBtn: {
    flex: 1,
    minWidth: "45%" as any,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceLight,
  },
  soundSetBtnActive: {
    borderColor: C.accent,
    backgroundColor: C.accentDim,
  },
  soundSetLabel: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 13,
    color: C.textSecondary,
  },
  soundSetLabelActive: {
    color: C.accent,
  },
  tripleRow: {
    flexDirection: "row",
    gap: 8,
  },
  tripleBtn: {
    flex: 1,
    alignItems: "center" as const,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceLight,
  },
  tripleBtnActive: {
    borderColor: C.accent,
    backgroundColor: C.accentDim,
  },
  tripleBtnText: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 13,
    color: C.textSecondary,
  },
  tripleBtnTextActive: {
    color: C.accent,
  },
  toggleRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceLight,
  },
  toggleLabel: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 14,
    color: C.textSecondary,
  },
  offsetRow: {
    flexDirection: "row",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: 8,
  },
  offsetBtn: {
    width: 44,
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceLight,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  offsetBtnText: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 13,
    color: C.text,
  },
  offsetResetBtn: {
    borderColor: C.accentMuted,
    backgroundColor: C.accentDim,
    width: 52,
  },
  offsetResetText: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 14,
    color: C.accent,
  },
  offsetHint: {
    fontFamily: "SpaceGrotesk_400Regular",
    fontSize: 10,
    color: C.textTertiary,
    textAlign: "center" as const,
    letterSpacing: 0.5,
  },
  themeScroll: {
    flexDirection: "row-reverse",
    gap: 10,
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  themeChip: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: C.border,
    alignItems: "center",
    justifyContent: "center",
  },
  customChip: {
    borderStyle: "dashed" as any,
  },
  themeDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  themeCheck: {
    position: "absolute",
  },
  customPickerContainer: {
    marginTop: 14,
    gap: 12,
  },
  hueTrackWrapper: {
    height: 32,
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  hueTrack: {
    height: 14,
    borderRadius: 7,
  },
  hueThumb: {
    position: "absolute",
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 3,
    left: 4,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 3,
      },
      android: { elevation: 4 },
      web: { boxShadow: "0 2px 6px rgba(0,0,0,0.4)" },
    }),
  },
  hexRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  hexPreview: {
    width: 28,
    height: 28,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: C.border,
  },
  hexInput: {
    flex: 1,
    height: 36,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 14,
    color: C.text,
    backgroundColor: C.surfaceLight,
  },
  hubImageCard: {
    marginTop: 10,
    backgroundColor: C.surface,
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: C.border,
  },
  hubImageTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  hubImageThumb: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  hubImageChips: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  beatTypeChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 14,
    borderWidth: 1,
  },
  beatTypeChipText: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 11,
    color: C.text,
  },
  hubImageRemove: {
    padding: 2,
  },
  addHubImageBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 10,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed" as any,
    backgroundColor: C.surface,
  },
  addHubImageText: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 13,
    color: C.text,
  },
  trackingBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  trackingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: C.success,
  },
  trackingText: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 12,
    color: C.text,
    flex: 1,
  },
  trackingStopBtn: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  trackingStopText: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 11,
    color: "#fff",
  },
  addRoomForm: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    gap: 8,
    borderStyle: "dashed" as any,
  },
  addRoomHint: {
    fontFamily: "SpaceGrotesk_400Regular",
    fontSize: 12,
    color: C.textSecondary,
  },
  addRoomRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  addRoomSaveBtn: {
    width: 42,
    height: 42,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  addRoomBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderWidth: 1,
    borderRadius: 10,
    borderStyle: "dashed" as any,
    marginTop: 4,
  },
  addRoomBtnText: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 13,
    color: C.text,
  },
  roomEmptyHint: {
    fontFamily: "SpaceGrotesk_400Regular",
    fontSize: 12,
    color: C.textTertiary,
    textAlign: "center",
    paddingVertical: 8,
  },
  roomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 6,
  },
  roomInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
  },
  roomName: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 13,
    color: C.text,
    flex: 1,
  },
  roomActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  roomStartBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  resetButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(248, 81, 73, 0.3)",
    backgroundColor: "rgba(248, 81, 73, 0.08)",
  },
  resetButtonText: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 13,
    color: "#F85149",
  },
  resetConfirmBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(248, 81, 73, 0.3)",
    backgroundColor: "rgba(248, 81, 73, 0.06)",
    padding: 16,
    gap: 14,
    alignItems: "center",
  },
  resetConfirmText: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 13,
    color: C.textSecondary,
    textAlign: "center",
    lineHeight: 20,
  },
  resetConfirmButtons: {
    flexDirection: "row",
    gap: 10,
    width: "100%",
  },
  resetCancelBtn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceLight,
  },
  resetCancelText: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 13,
    color: C.textSecondary,
  },
  resetConfirmBtn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#F85149",
  },
  resetConfirmBtnText: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 13,
    color: "#fff",
  },
  loggingInfoContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  loggingInfoSheet: {
    backgroundColor: C.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: C.border,
    padding: 24,
    width: "100%",
    maxWidth: 480,
  },
  loggingInfoHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 6,
  },
  loggingInfoTitle: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 18,
    color: C.text,
  },
  loggingInfoSubtitle: {
    fontFamily: "SpaceGrotesk_400Regular",
    fontSize: 13,
    color: C.textSecondary,
    marginBottom: 16,
  },
  loggingInfoCard: {
    backgroundColor: C.surfaceLight,
    borderRadius: 12,
    padding: 14,
    gap: 12,
  },
  loggingInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  loggingInfoText: {
    fontFamily: "SpaceGrotesk_400Regular",
    fontSize: 13,
    color: C.text,
    flex: 1,
  },
  loggingInfoFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 14,
    marginBottom: 16,
  },
  loggingInfoFooterText: {
    fontFamily: "SpaceGrotesk_400Regular",
    fontSize: 11,
    color: C.textTertiary,
  },
  loggingInfoCloseBtn: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 12,
  },
  loggingInfoCloseBtnText: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 14,
    color: C.white,
  },
  soundSetAddBtn: {
    borderStyle: "dashed" as any,
    borderColor: C.border,
  },
});

export const make_csStyles = (C: typeof Colors) => StyleSheet.create({
  editorContainer: {
    marginTop: 12,
    backgroundColor: C.surfaceLight,
    borderRadius: 12,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  editorHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  editorTitle: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 14,
    color: C.text,
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  fieldLabel: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 12,
    color: C.textSecondary,
    width: 60,
  },
  nameInput: {
    flex: 1,
    fontFamily: "SpaceGrotesk_400Regular",
    fontSize: 13,
    color: C.text,
    backgroundColor: C.surface,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: C.border,
  },
  sampleSection: {
    gap: 6,
    borderTopWidth: 1,
    borderTopColor: C.border,
    paddingTop: 10,
  },
  sampleHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sampleTitle: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 12,
    color: C.text,
  },
  previewBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: C.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: C.border,
  },
  pickerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  pickerLabel: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 11,
    color: C.textTertiary,
    width: 44,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    flex: 1,
  },
  chip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surface,
  },
  chipText: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 10,
    color: C.textSecondary,
  },
  durationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  durationControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  durationBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
  },
  durationValue: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 13,
    color: C.text,
    minWidth: 36,
    textAlign: "center",
  },
  customSampleInfo: {
    gap: 4,
  },
  customSampleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: C.surface,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: C.border,
  },
  customSampleName: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 11,
    color: C.text,
    flex: 1,
  },
  removeSampleBtn: {
    padding: 2,
  },
  recordingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingVertical: 4,
  },
  recordingIndicator: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  recordingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  recordingText: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 11,
    color: "#F85149",
  },
  recordImportRow: {
    flexDirection: "row",
    gap: 8,
  },
  recordActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    flex: 1,
    justifyContent: "center",
  },
  recordActionText: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 11,
    color: "#fff",
  },
  editorActions: {
    flexDirection: "row",
    gap: 10,
    justifyContent: "flex-end",
  },
  deleteBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(248, 81, 73, 0.3)",
    backgroundColor: "rgba(248, 81, 73, 0.08)",
  },
  deleteBtnText: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 12,
    color: "#F85149",
  },
  saveBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  saveBtnText: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 12,
    color: C.white,
  },
});

export const kbStyles = StyleSheet.create({
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 11,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  actionLabel: {
    fontFamily: "SpaceGrotesk_400Regular",
    fontSize: 14,
    flex: 1,
  },
  keyBadge: {
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    minWidth: 48,
    alignItems: "center",
  },
  keyText: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 12,
  },
  resetBtn: {
    alignSelf: "flex-end",
    marginBottom: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
  },
  resetBtnText: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 12,
  },
  overlayBg: {
    position: "absolute",
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: "rgba(0,0,0,0.7)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
  },
  overlayCard: {
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    minWidth: 260,
    gap: 8,
  },
  overlayTitle: {
    fontFamily: "SpaceGrotesk_700Bold",
    fontSize: 16,
    marginBottom: 4,
    textAlign: "center",
  },
  overlayActionLabel: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 13,
    textAlign: "center",
    marginBottom: 8,
  },
  overlayHint: {
    fontFamily: "SpaceGrotesk_400Regular",
    fontSize: 12,
    textAlign: "center",
    opacity: 0.7,
  },
  overlayConflict: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 12,
    color: "#FF6B6B",
    textAlign: "center",
  },
  overlayCancel: {
    marginTop: 8,
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
  },
  overlayCancelText: {
    fontFamily: "SpaceGrotesk_500Medium",
    fontSize: 13,
  },
  savedToast: {
    alignItems: "center",
    paddingVertical: 8,
    marginTop: 8,
  },
  savedToastText: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontSize: 13,
  },
});
